# Generated by Django 5.2 on 2025-05-07 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
                ('codigo_acceso', models.CharField(max_length=10, unique=True)),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'Borrador'), (3, 'Eliminado')], default=1)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='general.curso')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.curso')),
            ],
        ),
    ]
