# Generated by Django 5.2 on 2025-05-08 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('contenido', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.curso')),
                ('reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('reportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
