# Generated by Django 5.1.3 on 2025-05-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='nombre',
        ),
        migrations.AddField(
            model_name='examen',
            name='entregas_tardias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha_fin',
            field=models.DateField(default='2025-06-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha_inicio',
            field=models.DateField(default='2025-06-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examen',
            name='titulo',
            field=models.CharField(default='2025-06-30', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examen',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.curso'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.examen')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pregunta')),
            ],
        ),
    ]
