# Generated by Django 5.1.3 on 2025-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_remove_examen_fecha_creacion_remove_examen_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
