# Generated by Django 5.1.3 on 2025-05-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_examen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso')], default='abierta', max_length=20),
        ),
    ]
