# Generated by Django 5.1.3 on 2025-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntaje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
