# Generated by Django 5.2 on 2025-05-28 04:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_actividad_fecha_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionGlobalIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_global', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionPorPreguntaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_individual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calificacion_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_individuales', to='general.calificacionglobalia')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.examen')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
