# Generated by Django 5.2 on 2025-05-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_calificacionglobalia_calificacionporpreguntaia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroalimentacionIA',
            fields=[
                ('id_retroalimentacion_ia', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'examen')},
            },
        ),
    ]
