# Generated by Django 5.2 on 2025-05-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_retroalimentacionia'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacionia',
            name='id_calificacion_global',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retroalimentacion_ia', to='general.calificacionglobalia'),
        ),
    ]
