# Generated by Django 5.2 on 2025-05-28 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0016_retroalimentacionia_id_calificacion_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_sugerida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retroalimentacion_ia', models.TextField()),
                ('criterios_utilizados', models.TextField()),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('confirmada_por_docente', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_ia', to='general.envio')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioCalificacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje_programacion', models.CharField(help_text='Lenguaje de programación a evaluar (ej: Python, Java, JavaScript)', max_length=50)),
                ('criterios_evaluacion', models.TextField(help_text='Describe los criterios que la IA debe usar para calificar el código (ej: funcionalidad, eficiencia, estilo)')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('instrucciones_adicionales', models.TextField(blank=True, help_text='Instrucciones específicas para la IA sobre cómo evaluar el código')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criterio_ia', to='general.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_rendimiento', to='general.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de Rendimiento',
                'verbose_name_plural': 'Reportes de Rendimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
